### ISSUE TITLE
`import with` should allow constant as LHS of `as`

### ISSUE THREAD

**Issue by airbornemint** [observablehq/parser#102]
See for example https://observablehq.com/@airbornemint/units

I would like to import it using

```
import { m } with { "," as thousands_separator } from "@airbornemint/units"
```

But that gives me a parse error and I have to use two cells, one to define `new_thousands_separator = ","` and the other to `import { m } with { new_thousands_separator as thousands_separator } from "@airbornemint/units"`, which seems unnecessarily verbose for what is basically a module-level configuration parameter specified at the time of import.

**Comment by mbostock** [comment]
We’re not planning on doing this with import syntax, but we are considering a variety of other improvements to code reuse and importing. See this experiment, for example:

https://observablehq.com/@mbostock/dataflow

More ideas and discussion welcome, but closing this issue as we’re not planning on doing it in the near future.

**Comment by airbornemint** [comment]
@mbostock My take on this is that a. importing modules in Observable is already a hot mess (yes, I realize this mess is mostly inherited from JS), as evidenced by the very existence of [the require debugger](https://observablehq.com/@observablehq/module-require-debugger) and that b. adding one more syntax for importing a module is not helping. If this is part of some big plan that results in all import syntaxes converging on this one, fine; otherwise, concerned.
