### ISSUE TITLE
SyntaxError when destructuring onto instance properties

### ISSUE THREAD

**Issue by mootari** [observablehq/parser#182]
**Describe the bug**

**Demo:** https://observablehq.com/d/1fb03f01444425d2

Given a cell `foo` with
```javascript
foo = "bar"
```
when defining a cell where the value is referenced as a destructuring default for an instance property:
```javascript
function Test1(opts = {}) {
  ({a: this.a = foo} = opts);
}  
```
Observable will erroneously report
```
SyntaxError: Assignment to constant variable foo
```
To avoid the error, the cell value has to be assigned to an intermediate variable.

For example, the following pattern works:
```javascript
function Test2(opts = {}) {
  const _foo = foo;
  ({a: this.a = _foo} = opts);
}  
```
as does:
```javascript
function Test3(opts = {}, bar = foo) {
  ({a: this.a = bar} = opts);
}  
```

**Comment by mbostock** [comment]
@mootari Done, thanks! We’ll look at this one soon.
