### ISSUE TITLE
Can't require @observablehq/parser in an Observable notebook

### ISSUE THREAD

**Issue by asg017** [observablehq/parser#24]
jsdelivr [doesn't know how to use this package](https://www.jsdelivr.com/package/npm/@observablehq/parser) because there's no `"main"` specified in `package.json`, so a `parser = require('@observablehq/praser')` in observable will fail.

[more info in this notebook](https://beta.observablehq.com/d/5720deb83ebe0fc6)

**Comment by tmcw** [comment]
With 1.1.3, we now include a UMD dist, so

```
parser = require('@observablehq/parser')
```

Works in Observable, and other AMD/UMD/CJS environments.
