### ISSUE TITLE
example of using parser with runtime and inspector

### ISSUE THREAD

**Issue by lab4quant** [observablehq/parser#26]
Hello, please provide example of using `parser` with `runtime` and `inspector`
Thank you!

**Comment by bryangingechen** [comment]
Coincidentally, I've recently been playing around with the parser in [an Observable notebook](https://observablehq.com/d/c5efd660b44c143c) forked from @asg017's notebook in #25 (hope that's OK, Alex!). In that notebook you can find a very rough (and probably buggy) function which converts a notebook JSON object (which you can get by copying and pasting the response from the Observable API's /document/ endpoint) into a runtime V1 module. Hope it helps!

**Comment by lab4quant** [comment]
@bryangingechen , thank you, it helps!
